# Generated by Django 4.0 on 2023-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_cast_movie_crew_movie_reviews_movie_storyline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ott',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
